/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jtqiu' at '8/29/16 10:03 PM' with Gradle 2.9
 *
 * @author jtqiu, @date 8/29/16 10:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
